### ISSUE TITLE
Add support for MPL115A2 - I2C Barometric Pressure sensor

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#111]
Freescale MPL115A2 is a great low-cost sensing solution for measuring barometric pressure at 1.5 hPa resolution.
https://www.adafruit.com/product/992
https://github.com/adafruit/Adafruit_MPL115A2

w/ @fisherba

**Comment by aufdenkampe** [comment]
Barebones implementation from @ehost11: https://github.com/ehost11/EnviroDIY_Mayfly_Logger/blob/master/capstone/BaroPressureBarebones/BaroPressureBarebones.ino

**Comment by SRGDamia1** [comment]
@bschulz1701 version is now cleaned and in the develop branch.  I don't have a sensor to test it out, though.

**Comment by fisherba** [comment]
@SRGDamia1, I just tested the MPL115A2 in *develop* using simple_logging.ino and it works like a charm. thank you thank you!
