### ISSUE TITLE
Fix "synchronize RTC with NIST" for GPRSBee (SIM800)

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#136]
@fisherba and I have hardly gotten this to work in the last few months, so we're manually sycning the RTC.

I suspect that for the GPRSBee (SIM800), we need more time to power up the radio, get it to find a signal and then connect to NIST.

@SRGDamia1, can we add a longer warmup & attempt period when the modem is a SIM800? Where in the code would we do this?

Usually our code shows that we do have a modem signal, but by then it might not be trying to sync.
BTW, we have found that it is necessary to have a battery connected to the Mayfly to get the GPRSBee (SIM800) to work -- USB power is not enough.

**Comment by SRGDamia1** [comment]
Right now it should be set to try for 50 seconds to connect to the internet in the begin function before attempting to synchronize.  In the getNISTTime() function it only tries to connect for a single second, only as a quick verification that there is an internet connection before attempting the TCP connection. Can you, as always, post a debug and deep debug log (using the debugging in the LoggerModem.h)?

The GPRSBee (SIM800) _**requires** more power than is provided by the Mayfly alone_, whether the Mayfly is attached to USB or is running off a battery.  You should always have a battery attached directly to the GPRSBee (SIM800) or a battery attached to the Mayfly with the battery jumper running between the second Mayfly battery plug and the GPRSBee (SIM800).  (Or a battery attached to the Mayfly and the solder jumper connected to allow the bee power pin direct access to the battery.)  While connecting to the internet and sending data, the SIM800 can draw up to 2 amps of power.  If there isn't a battery directly connected to provide it with that amperage, the max available to from the Mayfly is less than 0.5A.  You'd be lucky if it connects at all.  Shannon added the extra solder jumper on the Mayfly 0.5b just for modems that don't have external battery attachments and need more than 0.5A power.

**Comment by SRGDamia1** [comment]
I've made some changes both in this library and in TinyGSM.  Have you noticed any improvement?

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for these effort to improve NIST sync. 

Both @fisherba and I have seen an increase in the number of successes with the 120 second warm up relative to the shorter times. However, it still isn't successful 100% of the time (maybe only barely 50% of the time). Also, that extra wait seems extra burdensome as we are developing and testing sketches for deployment.

I'm now thinking that we should eliminate NIST sync during startup. Because the startup functions do tell us the time via the serial monitor, we can easily do a visual check to see if they are within a minute of our computer, so it all seems a bit unnecessary.

I like the idea of doing NIST sync once a week or so, but at noon rather than midnight, so that it doesn't push the battery below the low-battery threshold and shut down the Mayfly.

The NIST sync via radio would be a very nifty separate utility that a user could run once when setting up a station, as an alternate approach to the [adjust](https://github.com/EnviroDIY/Sodaq_DS3231/tree/master/examples/adjust) or  [PCsync](https://github.com/EnviroDIY/Sodaq_DS3231/tree/master/examples/PCsync) utilities at https://github.com/EnviroDIY/Sodaq_DS3231.

**Comment by aufdenkampe** [comment]
Removing NIST sync during startup/setup is the first thing to try as the solution to #163.

**Comment by SRGDamia1** [comment]
Have any of the updates to TinyGSM made any difference with this?

**Comment by neilh10** [comment]
@aufdenkampe I agree. My 2cents based on using a low power 500mAh battery for test purpese, is that   NISTsync on startup should only be invoked 1) if the system needs time (1st power up or dead RTC batter) AND 2) there is adequate power available in the battery. 
I've put a discussion and data in #163

**Comment by SRGDamia1** [comment]
I think the reason the NIST sync probably fails is that NIST actually closes the TCP connection so quickly that the SIM800 actually sends out the socket closed notice before it sends out the notice of having received a reply.  I'm not sure there's much that can be done to fix that.

**Comment by SRGDamia1** [comment]
Some of this could possibly be fixed by using either UDP or the SIM800's internal NTP ability. I'm not sure how to solve the time zone issue though.

**Comment by SRGDamia1** [comment]
I'm pretty sure that any tailing issues with the SIM800 syncing are related to NIST closing the connection too fast and not in this library.
