### ISSUE TITLE
Allow i2c sensors to be fed a two-wire instance rather than always using default

### ISSUE THREAD

**Issue by SRGDamia1** [EnviroDIY/ModularSensors#149]
Similar to the way all serial sensors require a stream as input, instead of building the stream internally.  This is not supported by all of the sensor libraries, but could be implemented where it would be supported.

Unfortunately, unlike stream and serial, the software I2C library currently in use in the paleo terra branch doesn't share a common two wire parent, so it wouldn't necessarily help with those sensors.

**Comment by SRGDamia1** [comment]
Reading around, it doesn't look like any software I2C library supports this kind-of functionality.  So this really would only be helpful for SAMD boards or with multiple possibilities for hardware I2C.  To allow software I2C, some specific Software I2C library would have to be built in (and thus required) for each I2C module.

**Comment by SRGDamia1** [comment]
I put in a PR to the AVR core to make the functions virtual.

**Comment by aufdenkampe** [comment]
@SRGDamia1, you rock!

**Comment by SRGDamia1** [comment]
This is now done, where possible (which isn't that many places).

**Comment by aufdenkampe** [comment]
Did your PR to the AVR code get pulled into a release?

**Comment by SRGDamia1** [comment]
No.  It's here: https://github.com/arduino/ArduinoCore-avr/pull/288

**Comment by aufdenkampe** [comment]
Thanks for that update and the link.
