### ISSUE TITLE
Turning on debugging causes native USB to fail on SAMD21

### ISSUE THREAD

**Issue by SRGDamia1** [EnviroDIY/ModularSensors#183]
Turning on the extra debugging print statements may cause the native USB (Serial on a Feather M0) to stop responding. No clue why this is happening.  I spent way too long fidding with it.  Apparently identical lines of code work and don't.  I think it must have something to do with the timing.

**Comment by SRGDamia1** [comment]
I think I've caught all the problems with the debugging and fixed them with #262.  The problem is when a serial.print is called in any way before a serial.begin.

**Comment by aufdenkampe** [comment]
@SRGDamia1, I'm not sure that you intended to refer to #262 here. Which were the issues/commits that fixed this?

**Comment by SRGDamia1** [comment]
Yes, it will be in #262, commits 1577d6d60f284997aef9f6bb9130027423e283bc, 02cd9b796cd082f3a211a1ee8dbab377030a5dbe, and ed6ee06f4cd4af6fd05a0ca96b58f91ad65b3607

**Comment by aufdenkampe** [comment]
Ah! I see them in #256. Thanks!
