### ISSUE TITLE
Document Atlas sensors

### ISSUE THREAD

**Issue by SRGDamia1** [EnviroDIY/ModularSensors#226]
@acgold - I'd also love if you could write something up to go into the wiki similar to the documentation I have for the other sensors.

**Comment by acgold** [comment]
Here's some text about the Atlas Sensors. I included a link to a carrier board that I made and have been using, but feel free to remove it.  I'm planning on writing a blog post on EnviroDIY in the next couple months and will include it then as well. Let me know if there's anything else I can help with.  Thanks!

Atlas Scientific sensors can communicate with the board using UART or I2C protocols, but the code in ModularSensors uses I2C. Atlas scientific sensors are shipped with probes and sensor chips that communicate using UART by default. Data sheets, found of the Atlas Scientific website (example: https://www.atlas-scientific.com/_files/_datasheets/_circuit/DO_EZO_Datasheet.pdf?), show how to manually switch the chips to I2C as well as how to communicate with the probe. The chips have operating voltages between 3.3V and 5V. The probes and sensors can be calibrated using sketches provided by Atlas Scientific on their website. Atlas Scientific recommends that you integrate their sensor chips into a board, so you can buy one from them or make your own (example: https://github.com/acgold/Atlas-Scientific-Carrier-Board).

**Comment by SRGDamia1** [comment]
Thank you!
