### ISSUE TITLE
Update docs/wiki with new constructors and begin functions

### ISSUE THREAD

**Issue by SRGDamia1** [EnviroDIY/ModularSensors#242]
It's a never ending battle - keeping the documentation up to date!

- [x] Data publishers
    - [ ] EnviroDIY
    - [ ] ThingSpeak
- [ ] Logger
- [ ] VariableArray
- [ ] Variables
    - [ ] All variable subclasses

**Comment by aufdenkampe** [comment]
@SRGDamia1, thanks for staying on top of the documentation! It is really important!

**Comment by SRGDamia1** [comment]
So I'm not sure exactly what functions I though needed to be documented back then, but I'm sure they now are.
