### ISSUE TITLE
baro_rho_correction.ino no Unable to write to SD card!

### ISSUE THREAD

**Issue by gcutrell** [EnviroDIY/ModularSensors#243]
Using libraryVersion = "0.21.1" for current baro_rho_correction.ino and receives 
"Successfully connected to SD Card with card/slave select on pin 12
Successfully connected to SD Card with card/slave select on pin 12
Unable to write to SD card!"

No modem is attached although code is left in.

**Comment by jtbthe3** [comment]
same

**Comment by SRGDamia1** [comment]
I'll look into it as soon as I can

**Comment by SRGDamia1** [comment]
Fixed in 0.21.2
