### ISSUE TITLE
Hangup in calcfunc variable for library 0.21.2

### ISSUE THREAD

**Issue by gcutrell** [EnviroDIY/ModularSensors#249]
During the first measurement sequence using a variable based of a calculated function instead of data being read in the program outputs 
"This logger has a variable array with 6 variables, of which 5 come from 3 sensors and 1 are calculated.
Logger object created
S"

and then gets hung up. Strangely I thought the variable array occurs during the initial startup. If I take away the calculated variable it works fine. I've commented out all my non-Module library code in the attached file and am only now measuring from a bme280 and ds18. My function is trying to calculate mean sea level pressure using station pressure from the bme280, air temp from the ds18, and a known altitude. 

[UWINBUOY2.txt](https://github.com/EnviroDIY/ModularSensors/files/2998921/UWINBUOY2.txt)

**Comment by aufdenkampe** [comment]
We can confirm that this issue no longer exists in the current releases.
