### ISSUE TITLE
Add a class for a DHT22/DHT11 digital humidity and temperature sensor

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#30]
This would also be a relative simple example to describe how to create new sensor sub-classes.

These sensors are used in Workshop Sketch 6.
* https://github.com/EnviroDIY/EnviroDIY_Mayfly_Logger/tree/master/workshop/mayfly_06_humidity-temp

and in this potential workshop sketch:
* https://github.com/EnviroDIY/EnviroDIY_Mayfly_Logger/blob/Mayfly_11_DT-LED/workshop/mayfly_10b_DHT_LED/mayfly_10b_DHT_LED.ino

Info on these sensors can be found at:
* http://wiki.seeed.cc/Grove-TemperatureAndHumidity_Sensor/
* http://wiki.seeed.cc/Grove-Temperature_and_Humidity_Sensor_Pro/

We've used the Adafruit DHT-sensor-library:
* https://github.com/adafruit/DHT-sensor-library/tree/c97897771807613d456b318236e18a04b013410b

**Comment by SRGDamia1** [comment]
In progress in https://github.com/EnviroDIY/ModularSensors/tree/DHTSensor

**Comment by SRGDamia1** [comment]
Closed by #40.
