### ISSUE TITLE
Errors in library manifest

### ISSUE THREAD

**Issue by pfeerick** [EnviroDIY/ModularSensors#338]
The `_note` on all of these lines are invalid. Additionally, L150 should be url, not version ;)

https://github.com/EnviroDIY/ModularSensors/blob/260eacbd2b9a9a94e4d162bec53977cb09cb2c48/library.json#L150-L157

**Comment by SRGDamia1** [comment]
I don't think these are problems:  https://github.com/platformio/platformio-core/issues/3741#issuecomment-745371035
