### ISSUE TITLE
Developer Setup instructions lib_extra_dirs warning

### ISSUE THREAD

**Issue by mbarneytu** [EnviroDIY/ModularSensors#352]
The platformio.ini provided on the [Developer Setup page](https://envirodiy.github.io/ModularSensors/page_for_developers.html) generates a warning on Clean or Build:
`Warning! `lib_extra_dirs` configuration option is deprecated in section [platformio]! Please move it to global `env` section
`

**Comment by SRGDamia1** [comment]
Sorry.  This is fixed now, but hasn't been pushed to master yet.

**Comment by aufdenkampe** [comment]
Thanks @mbarneytu for catching this and @SRGDamia1 for fixing!
