### ISSUE TITLE
AOSongAM2315.cpp memory leak

### ISSUE THREAD

**Issue by neilh10** [EnviroDIY/ModularSensors#399]
AOSongAM2315.cpp has a memory leak, my fix is here
https://github.com/neilh10/ModularSensors/commit/8c9466447078500c6d35706fdd6c01b82444197d

I'm generating this issue to track it for the master release, 
I'm still confirming the solution and my tracking is here.
https://github.com/neilh10/ModularSensors/issues/102

I can submit a fix if its of interest when I've done some more testing.

**Comment by SRGDamia1** [comment]
I cherry-picked your commit with the fix.
