### ISSUE TITLE
Fully support Y4000 Multiparameter Sonde

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#420]
We've long had some support for [YosemiTech's Y4000 Multiparameter Sonde](http://en.yosemitech.com/aspcms/product/2020-5-8/95.html), but it was not fully functional or tested.

For more details on known issues, see:
- https://github.com/EnviroDIY/YosemitechModbus/issues/13

**Comment by aufdenkampe** [comment]
Y4000 is now working well, and providing Chlorophyll and blue-green algal values.

**Comment by neilh10** [comment]
yeah. !!

**Comment by GArrigotti-cws** [comment]
Once we get those new wings I’ll test.
