### ISSUE TITLE
conductivity test Y520-A

### ISSUE THREAD

**Issue by fisherba** [EnviroDIY/ModularSensors#63]
@SRGDamia1, do you have a conductivity sensor (Y520) to test the sketches? We are *pretty sure* the one we have is faulty, but it would be nice to have another testing the sketch.

**Comment by SRGDamia1** [comment]
Yes, though I haven't started testing it yet.  I'm still fooling with the non-wiping turbidity.  I'll pull it out next.

**Comment by fisherba** [comment]
Thanks!

**Comment by SRGDamia1** [comment]
Works, per #71
