### ISSUE TITLE
Use Doxygen automated documentation generator

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#75]
@SRGDamia1, are you inspired by http://odm2.github.io/ODM2PythonAPI?
It would be awesome to have this, to get others to start contributing.

I bet @lsetiawan would be happy to provide guidance and help.

**Comment by SRGDamia1** [comment]
How does it work with C++?

**Comment by lsetiawan** [comment]
Not sure, I have not explored that. @ocefpaf, Do you know if sphinx can do C++?

**Comment by SRGDamia1** [comment]
I have a lot of comments and "doc-strings" in this repo, but everything is in C++

**Comment by ocefpaf** [comment]
I never used it but there is a sphinx extension to `Doxygen` that can do that.

https://breathe.readthedocs.io/en/latest/

**Comment by aufdenkampe** [comment]
I've learned a bit more about Doxygen, and I think it is the right choice for these Arduino libraries. https://en.wikipedia.org/wiki/Doxygen.
Changing the name of this issue. Thanks all for the feedback.

**Comment by SRGDamia1** [comment]
Three years later, this is done.

**Comment by aufdenkampe** [comment]
@SRGDamia1, thank you for this very impressive effort (and outcome!) on your end!
