### ISSUE TITLE
Change Conductivity units from mS/cm to microS/cm for Yosemitech Y520

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/ModularSensors#96]
The default output units for Yosemitech Y520 sensor is mS/cm (milli Siemens per centimeter), but nearly everyone looking at freshwater uses µS/cm (microS/cm, sometimes written as uS/cm). This includes the EnviroDIY Data Portal.

It seems we should provide the unit conversion in this library, rather than in https://github.com/EnviroDIY/YosemitechModbus.

@SRGDamia1, Where/how do we do that?

**Comment by aufdenkampe** [comment]
@SRGDamia1, I'm happy to do code changes and test, if you point me to where it might be best to change. It would be nice to get this done before we issue the next release.

What do you think?

**Comment by SRGDamia1** [comment]
It's in the YosemitechParent.cpp, in addSingleMeasurementResult.

**Comment by aufdenkampe** [comment]
Thank you! I appreciate you taking care of this. 

Seeing your commit helps me better understand ModularSensors in general, and also the fix to https://github.com/EnviroDIY/YosemitechModbus/issues/9 helped with understanding, especially after finding the code here: https://github.com/EnviroDIY/YosemitechModbus/blob/master/src/YosemitechModbus.cpp#L348-L357.

Thanks!
